# Generated by Django 3.2.4 on 2021-06-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, unique=True)),
                ('categoria', models.CharField(max_length=40)),
                ('precio', models.FloatField()),
                ('imagen', models.FileField(upload_to='')),
                ('fecha_creacion', models.DateTimeField()),
            ],
        ),
    ]
