# Generated by Django 3.2.4 on 2021-06-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete01', '0002_auto_20210618_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_base',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jaguarete01.categoria'),
        ),
    ]
