# Generated by Django 3.2.4 on 2021-06-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete01', '0003_alter_producto_categoria_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_base',
        ),
    ]
