# Generated by Django 3.2.4 on 2021-06-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete01', '0005_producto_categoria_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
