# Generated by Django 3.2.4 on 2021-06-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete01', '0010_alter_producto_categoria_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
