# Generated by Django 3.2.4 on 2021-06-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete01', '0012_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalle',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
