# Generated by Django 3.2.4 on 2021-06-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaguarete01', '0014_alter_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('can_add_productos', 'Can add productos'),)},
        ),
    ]
